architectures: amd64
debug: true
distribution: bookworm
donateUrl: https://www.debian.org
email: email@risserlabs.com
issuesUrl: https://bugs.debian.org
keyboardLayout: us
locale: en_US
mirror: http://deb.debian.org/debian/
mirrorSecurity: http://security.debian.org/
name: DEB Distro
releaseNotesUrl: https://www.debian.org/releases/bookworm/releasenotes
shortName: Debian
supportUrl: https://www.debian.org/support
version: 12
website: https://bitspur.com
lb:
  debianInstaller: cdrom # true|cdrom|netinst|netboot|businesscard|live|false
  debianInstallerGui: false
  debianInstallerDistribution: bookworm # daily|bookworm
overlays:
  apt: {}
  chromium: {}
  debianInstaller: {}
  easterEggs: {}
  example: {}
  firefox: {}
  firmware: {}
  grub: {}
  plymouth: {}
  sway: {}
  gnome:
    packages:
      highPriority: true
      mediumPriority: false
      lowPriority: false
  tools:
    packages:
      cli: true
      media: false
  flatpak:
    flatpaks: []
      # - com.belmoussaoui.Authenticator
      # - com.usebottles.bottles
  snap:
    snaps: []
  # dev: {}
  # onlyoffice: {}
  # waydroid: {}
  # ungoogledChromium: {}
  # librewolf: {}
